### PR TITLE
Update document control

### PR DESCRIPTION
**Pull request by SimonBiggs**
Hi @sjswerdloff,

Is it okay to be requesting review from you for these documents? This is not a review to verify that it meets regulatory requirements, instead, consider it a peer review designed to uphold a level of document quality.

Would that be okay?

---

I'll be making a follow up PR that adjusts the document layout according to the changes I have made within this document.

### CODE REVIEW

**Comment by sjswerdloff** [comment]
> Hi @sjswerdloff,
> 
> Is it okay to be requesting review from you for these documents? This is not a review to verify that it meets regulatory requirements, instead, consider it a peer review designed to uphold a level of document quality.
> 
> Would that be okay?
> 
> ---
> 
> I'll be making a follow up PR that adjusts the document layout according to the changes I have made within this document.

I'm fine with reviewing as a developer with basic knowledge of quality systems for regulated medical software.  YMMV.

**Comment by SimonBiggs** [comment]
> I'm fine with reviewing as a developer with basic knowledge of quality systems for regulated medical software. YMMV.

That would be perfect. Thanks @sjswerdloff :slightly_smiling_face:

**Comment by SimonBiggs** [comment]
(I've stopped my follow up changes, I'll leave this PR static now :slightly_smiling_face:)

**Review by sjswerdloff — APPROVED** [review]
There is a general assumption that git history will be permanent as a means of ensuring a proper permanent history (of the quality system, never mind the codebase).
What are the consequences of someone doing a rebase?
I'm not saying that is necessarily a problem, but I think it is worth thinking about.
There's something to be said for offline backups.

**Comment by SimonBiggs** [comment]
With the rebase question, I am using GPG signing of all of my commits. So others won't be able to mimic my commits while still having it be verified.

I haven't yet written that as a requirement into the QMS. Once I need to handle FDA approval the document signing requirements are quite specific. I figure, for now, solve the TGA and CE requirements, and then, if GPG signing is sufficient for FDA I can make that signing requirement as part of the QMS, and sign any remaining unsigned documents prior to seeking FDA approval.

Certainly offline backups will be helpful. I won't make it a requirement of my QMS just at the moment, but in effect having local git forks acts as a degree of redundancy for now.

**Pull request merged**
